app/models.py
from . import db
from sqlalchemy.sql import func
from werkzeug.security import generate_password_hash, check_password_hash
from . import login_manager
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return Admin.query.get(int(user_id))

class Student(UserMixin,db.Model):
    __tablename__ ="students"
    student_id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    phone = db.Column(db.Integer,unique = True)
    questions = db.Column(db.ARRAY(db.String))

    def get_id(self):
        return student_id


class Admin(db.Model):
    __tablename__ = "admins"
    admin_id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    email = db.Column(db.String())
    approved = db.Column(db.Boolean)
    pass_word= db.Column(db.String(255))
    

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_word = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_word,password)


    def __repr__(self):
        return f'User {self.username}'

class Question(db.Model):
    __tablename__ ="questions"
    question_id = db.Column(db.Integer, primary_key = True)
    question = db.Column(db.String())
    subject = db.Column(db.String(255))
    grade = db.Column(db.Integer)
    seen = db.Column(db.Boolean)
    answer = db.relationship('Answer',backref = 'question',lazy="dynamic")

class Answer(db.Model):
    __tablename__ = "answers"
    answer_id = db.Column(db.Integer, primary_key = True)
    answer = db.Column(db.String(255))
    question_id = db.Column(db.Integer,db.ForeignKey('questions.question_id'))

class CurrentQuestion(db.Model):
    __tablename__ = "currentquestions"
    question_id = db.Column(db.Integer, primary_key = True)
    question = db.Column(db.String())
    subject = db.Column(db.String(255))
    grade = db.Column(db.Integer)
    seen = db.Column(db.Boolean)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import RadioField, TextAreaField,StringField, PasswordField, SubmitField, BooleanField,FormField
from wtforms.validators import Required, Email, EqualTo
from wtforms import ValidationError
from ..models import Student

class quizForm(FlaskForm):
    Grade = StringField('Grade', validators=[Required()])
    Subject=RadioField('Label', choices=[('English', 'English'),('Science', 'Science'),('Kiswahili','Kiswahili'),('Math','Math')],validators=[Required()])
    question=TextAreaField('Question', validators=[Required()])
    A= TextAreaField('A', validators=[Required()])
    B= TextAreaField('B', validators=[Required()])
    C= TextAreaField('C', validators=[Required()])
    D= TextAreaField('D', validators=[Required()])
    Answer= TextAreaField('Answer', validators=[Required()])
    Submit =SubmitField('Submit')

class loginForm(FlaskForm):
    email = StringField('Your email address', validators=[Required(), Email()])
    password = PasswordField('Enter your password', validators=[Required()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Sign In')

class RegistrationForm(FlaskForm):
    name = StringField('Enter your username',validators = [Required()])
    mobile_phone = StringField('Enter your phone.no')
    submit = SubmitField('Sign Up')

    def validate_phone(self,data_field):
        if Student.query.filter_by(phone =data_field.data).first():
            raise ValidationError('Phone number already taken. Send join egg-unusual to +1415 523 8886 to start learning!')

app/__init__.py
from config import config_options
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_wtf.csrf import CSRFProtect
from flask_login import LoginManager
from flask_mail import Mail

mail = Mail()
db = SQLAlchemy()
bootstrap = Bootstrap()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'main.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import  render_template, request, url_for, abort, redirect,flash
from . import main
from .fill_db import questionAnswerTuples
from .. import db
from ..models import Question,Answer, Admin, Student
from .forms import quizForm, loginForm, RegistrationForm
from twilio.twiml.messaging_response import MessagingResponse

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/student')
def student():
    return render_template('student.html')

@main.route('/question', methods= ['POST'])
def receive_question():
    if not Question.query.filter_by(seen = False).all():
        questionAnswerTuples()
    msg = request.form.get('Body').lower()
    user = request.form.get('From').lower()
    print(user)
    response = MessagingResponse()
    text = ["Welcome to E-Learn!\nThis is an online platform for you to study \
    from the comfort of your home!.\n To start us off, what subject would youlike to study today? Math, Science, Kiswahili or English?\n ", 
    "Invalid option :(.\nPlease select between the following options: Math, English, Kiswahili, Science"]
    subjects = ["math", "english", "science", "kiswahili", "cre", "social studies" ]
    resp = ""
    current_subject = ""
    if msg == "join egg-unusual" or msg == "hi":
        response.message(text[0])
    elif msg in subjects:
        questions = Question.query.filter_by(subject = msg).all()
        if not questions:
            response.message(f"We currently don't have any questions for the subject {msg}. Check back in a day or two.")
        else:
            if len(questions)>5:
                questions = questions[0:5]
            for question in questions:
                question.seen = True
                db.session.commit()
                resp = resp + "\n" + question.question
            response.message(resp)
    elif msg.lower() == "done":
        questions = Question.query.filter_by(seen = True).all()
        print(questions)
        for question in questions:
            question.seen = False
            db.session.commit()
            answer = Answer.query.filter_by(question_id = question.question_id).first()
            resp = resp + "\n" + answer.answer
        response.message(resp)
    else:
        response.message(text[1])
    return str(response)

@main.route('/e-learn/Technicalsupport/', methods=['POST','GET'])
def exam_questions():
    form = quizForm()
    if form.validate_on_submit():
       subject= form.Subject.data
       answer = form.Answer.data 
       grade = form.Grade.data
       question = form.question.data + "\n" + "A. "+ form.A.data + "\n" + "B. "+ form.B.data + "\n" + "C. "+ form.C.data + "\n" + "D. "+ form.C.data + "\n"
       newQuiz = Question(question = question,subject = subject,grade = grade)
       db.session.add(newQuiz)
       db.session.commit()
       question = Question.query.filter_by(question = question).first()
       newAnsw = Answer(answer = answer,question_id =question.question_id )
       db.session.add(newAnsw)
       db.session.commit()
       return redirect(url_for('main.exam_questions'))
    return render_template('questions.html',form = form)
@main.route('/e-learn/login/', methods=['POST', 'GET'])
def login():
    form= loginForm()
    if form.validate_on_submit():
        user = Admin.query.filter_by(email= form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user, form.remember.data)
            return redirect(request.args.get('next') or url_for('main.exam_questions'))
        flash ('Invalid username or password')
    return render_template('login.html', form=form)
@main.route('/e-learn/signup', methods=['POST', 'GET'])
def signUp():
    form= RegistrationForm()
    if form.validate_on_submit():
        user = Student(name=form.name.data, phone=form.mobile_phone.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('main.student'))  
    return render_template('signup.html', form= form)

# @main.route('/teacher/question')
# def submit_question():
#     #to implement later
#     #might have forgotten some stuff. please list here
#     pass

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{%block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block styles%}

<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">

<link href="https://fonts.googleapis.com/css2?family=Itim&display=swap" rel="stylesheet">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">

<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">

{%endblock%}

{%block scripts%}

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>

{%endblock%}

app/templates/base1.html
{% extends 'bootstrap/base1.html'%}

{% block styles%}

<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">

<link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">

{%endblock%}

{%block scripts%}

<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>

{%endblock%}

app/templates/login.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container" style="font-size: 20px; font-family: 'Itim', cursive;">
    <div class="row">
        <div class="col-md-2"> </div>
        <div class="col-md-8 card mt-3 p-5"
            style="font-size: 20px; font-family: 'Merienda', cursive;  padding-top: 40px;">
            <h3 class="mt-3 pb-3 text-center">Login</h3>
            <hr>
            <!--Flash message -->
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            <!-- Login form -->
            {{wtf.quick_form(form)}}
            <p> Don't have an account? <a href="{{url_for('main.signUp')}}">Sign up here</a></p>
        </div>
        <div clas="col-md-2"> </div>
    </div>
</div>

{% endblock%}

app/templates/navbar.html
<!--Navbar -->
<nav class=" container-fluid mb-1 navbar navbar-expand-lg navbar-dark default-color sticky-top"
  style="font-size: 20px; font-family: 'Itim', cursive;">
  <a class="navbar-brand" href="{{url_for('main.index')}}">E-learn</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{url_for('main.index')}}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#about">AboutUs</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#subjects">Subjects</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true"
          aria-expanded="false">
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="{{url_for('main.signUp')}}">Signup</a>
          <a class="dropdown-item" href="{{url_for('main.login')}}">Login</a>
        </div>
      </li>
    </ul>
  </div>
</nav>
<!--/.Navbar -->

app/templates/questions.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container" style="font-size: 20px; font-family: 'Itim', cursive;">
    <div class="row">
        <div class="col-md-2"> </div>
        <div class="col-md-8 card mt-3 p-5"
            style="font-size: 20px; font-family: 'Merienda', cursive;  padding-top: 40px;">
            <h3 class="mt-3 pb-3 text-center">Questions</h3>
            <hr>
            <!--Flash message -->
            {% for message in get_flashed_messages() %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
            <!-- Login form -->
            {{wtf.quick_form(form)}}
        <div clas="col-md-2"> </div>
    </div>
</div>

{% endblock%}

app/templates/signup.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}


{% block content %}
<div class="container" style="font-weight: 400px; font-family: 'Itim', cursive;">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8 card mt-3 p-5" style="font-size: 20px; font-family: 'Merienda', cursive;  padding-top: 40px;">
    <h3 class="mt-3 pb-3 text-center">Student Registration</h3>
    <hr>
{{wtf.quick_form(form)}}
<p> Have have an account? <a href="{{url_for('main.login')}}">Login</a></p>

</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}

app/templates/student.html
{% extends 'base.html'%}
{%block content%}
<div class="container-fluid" style="font-size: 20px; font-family: 'Itim', cursive;
    background-image: url(../static/photos/back2.jpeg);
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center;
        
    ">
    <div>
        <h1 class=" text-white text-center pt-5">Welcome to e-learn platform Precious and very bright student</h1>
    </div>
    <div class="text-center">
        <img class="img-fluid" src="../static/photos/online.jpeg" style="width:500px;height:300px;">
    </div>
    <h1 class="text-center pt-5 text-white" >Let's get Started</h1>
    <div class="row text-white">
        <div class="col md-6">
            
                <div >
                <h2 class="display-4">Twilio</h2>
                <ul>
                    <li >
                        To access questions on whatsapp you will be required to text the word <span class="text-danger"><em>  "join egg-unusual" </em></span> to the number <span class="text-success">+1 (415) 523-8886.</span>
                    </li>
                    <li>
                        Twilio session ends after every 24 hrs which basically means that you are required to retext the word <span class="text-danger"><em>"join egg-unusual" </em></span> anytime you want to access twilio services.
                    </li>
                    <li>
                        Note that you are not eligible to receive our services if you are not registered in our website.
                    </li>
                </ul>

                </div>
    
        </div>

        <div class="col md-6">
            
                
            <h2 class="display-4">Questions</h2>
            <ul>
                <li>
                    You are required to choose the subject you want to learn from the various categories that our platform provides. i.e; [maths,english,science,kiswahili,social studies]
                </li>
                <!-- <li>
                    You are required to select your answer from the options you are provided with.i.e;<br>
                    [A,B,C,D].
                </li> -->
                <li>
                    Once you are done with selecting your answers,you are required to type the word <span class="text-danger"><em>"Done" </em></span> so as to receive your answers.
                </li>
                <!-- <li>
                    You can only make one selection from the answers provided.
                </li> -->
            </ul>
            
            
       
    </div>
        
    </div>

    <div class="text-white text-center pt-3">
        <h1>We are now all set</h1>
        <h3><em>Remember that successful people look like you!</em></h3>

    </div>

    
<footer class="page-footer font-small default-color">

    
    <div class="footer-copyright text-center  py-3">© 2020 Copyright:
      <a href="#"> e-learn.com</a>
    </div>
    
  
  </footer>
  
    
</div>
  {%endblock%}